### PR TITLE
Use docker-compose for postgres

### PR DESCRIPTION
**Pull request by MBuchalik**
I have migrated the backend to use an official postgres image. You can now start the backend using
```
docker-compose up
```
This will also start pgAdmin, so that you can view the content of the database.

What do you think about these changes?

Btw: I have updated the Readme file in many places.

### CODE REVIEW

**Review by dalex135 — APPROVED** [review]

**Review by dalex135 — APPROVED** [review]
Pulled and ran yml file. Everything is working properly.

**Comment by MBuchalik** [comment]
Awesome! From my point of view, this can then be merged 👍

**Review by vishwasanavatti — APPROVED** [review]
Looks great. I Could able to up the database using docker-compose up and ran the application, It just works fine.

**Review by vishwasanavatti — APPROVED** [review]

**Comment by MBuchalik** [comment]
Perfect! 👍 I will merge it then :)

**Pull request merged**
