### PR TITLE
Enhance the feature documentation

### PR DESCRIPTION
**Pull request by MBuchalik**
I have enhanced the feature documentation to include many more screenshots and descriptions.

Would be cool if we could merge this PR soon so that it does not become outdated again :D

### CODE REVIEW

**Comment by MBuchalik** [comment]
Marked this PR as a draft since I will change the folder structure (as described in https://github.com/Nasser-Eddin-Nasser/Digitact/pull/118#issuecomment-659368947).

**Comment by MBuchalik** [comment]
Alright, done with renaming the files.

**Comment by dalex135** [comment]
Quick question, are you guys finished with the user story - 51 (Full Review | App UI Review)?
I feel that the view of the app will change then. If the US is finished, I can review this.

**Comment by MBuchalik** [comment]
@dalex135 I am not a collaborator of User Story 51. But as far as I can see, the User Story will probably change some texts, but not the overall structure of the app. Also, in the acceptance criteria of US 51 it says that they should update the screenshots if needed. So, from my point of view, we could maybe merge this PR now and later update some of the screenshots again. What do you think about this? I am just worried that we will try to merge every PR on Sunday and this might lead to a big mess :D

**Review by Nasser-Eddin-Nasser — APPROVED** [review]

**Review by vishwasanavatti — APPROVED** [review]
Good job Martin. Looks good. ok to merge.

**Comment by dalex135** [comment]
@MBuchalik Yeah we can change it later if need.

**Review by dalex135 — APPROVED** [review]
Looks nice and neat. Great work!

**Comment by MBuchalik** [comment]
Perfect, thanks for your reviews! 🎉

**Pull request merged**
