### PR TITLE
Contact form - Frontend

### PR DESCRIPTION
**Pull request by dalex135**
@Bharathravi1995 
Please check the changes

### CODE REVIEW

**Comment by Bharathravi1995** [comment]
@dalex135 I have pushed some changes. Can u fetch the new changes and modify comments , eventemitter function handler, onValChanges as observer?

**Comment by dalex135** [comment]
@Bharathravi1995 
I made my changes. But now there is a major change in the comparison. There is a change between the real master branch and the master branch that appears in my comparison.

**Comment by Bharathravi1995** [comment]
> @Bharathravi1995
> I made my changes. But now there is a major change in the comparison. There is a change between the real master branch and the master branch that appears in my comparison.

It was due to unresolved merge conflicts. I have resolved it. Now you can able to see only your changes. Make sure always conflicts are resolved if any, before pushing any changes.

**Comment by Bharathravi1995** [comment]
@dalex135 There is an issue. When the fields are filled and close button is clicked and again filling form for the second time, the previous values are pre filled. So need to reset contactInfoObject on destroy.

**Comment by dalex135** [comment]
@Bharathravi1995 
I think I can merge now. I updated the code.

**Comment by Bharathravi1995** [comment]
> @Bharathravi1995
> I think I can merge now. I updated the code.

@dalex135  Seems fine now. I am merging this PR.

**Pull request merged**
