### PR TITLE
Applicant status in BE and HR

### PR DESCRIPTION
**Pull request by dalex135**

### CODE REVIEW

**Review by Nasser-Eddin-Nasser — COMMENTED** [review]
I ran the code and testit, it works perfectly, I found one small bug, after adding a comment by HR member, the comment will not be updated automatically.

**Review by Nasser-Eddin-Nasser — APPROVED** [review]
Bug fixed! It can be merged :)

**Review by Nasser-Eddin-Nasser — COMMENTED** [review]
I checked the Application and reviewed it with Alex. It'll be better to be reviewed from another collaborator before merging it!

**Comment by Bharathravi1995** [comment]
I am okay to merge it as well. @dalex135  can you resolve the conflict.

**Review by Bharathravi1995 — APPROVED** [review]
LGTM

**Comment by dalex135** [comment]
Corrected the conflicted. Hope I can merge it now.

**Pull request merged**
