### PR TITLE
Feature Documentation: HR-Monitor

### PR DESCRIPTION
**Pull request by dalex135**
Just created a PR to check whether I have taken the right approach. We can add images after the full review of the HR monitor(US 83).

### CODE REVIEW

**Comment by MBuchalik** [comment]
Shouldn't we create a separate feature documentation for the HR Monitor? I will soon extend the feature doc to include many more screens of the app. And this will make the document pretty long.

**Comment by dalex135** [comment]
Yeah, that can be done, but do we name our feature document? "HR-Module features"?

**Comment by MBuchalik** [comment]
Hmmm good question. How about "hr-monitor-features.md"? Or "features-hr-monitor.md"? (I personally prefer to use lowercase file names, but you can do as you like.)

**Comment by dalex135** [comment]
Yeah, better to have same name format. I'll do it as "features-hr-monitor.md". But will you keep the current feature doc name as the same?

**Comment by MBuchalik** [comment]
> But will you keep the current feature doc name as the same?

I can rename it as "features-app.md" or so in #121 . I will then also move the images from `docs/images/` to `docs/images/app/` so that you can place your images in `docs/images/hr-monitor/` (or similar).

**Comment by dalex135** [comment]
Cool!
Yeah, I'll create and place images there

**Review by vishwasanavatti — APPROVED** [review]
looks good. Good job Alex. ok to merge.

**Review by MBuchalik — APPROVED** [review]
LGTM 👍

**Review by Nasser-Eddin-Nasser — COMMENTED** [review]
It looks good, great job.

**Review by vishwasanavatti — APPROVED** [review]
LGTM. can be merged.

**Pull request merged**
